import { Inter } from "next/font/google";
import "../app/styles/home.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ParáMinas Açaí",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="header">
          <Link className="link-home" key="Home" href="/">Home</Link>
        </div>

        <div className="menu-container">
          {/* Container da imagem */}
          <div className="main-content">
            <img src="/acaiteriabanner.jpg" alt="Açaí" className="main-image" />
          </div>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}